funds:
  - name: "Azvalor Internacional FI"
    isin: "ES0112611001"
    category: "Global Flex-Cap Equity"
    morningstarId: "F00000WI0D"
    comment: "Comentario1"
  - name: "Azvalor Managers FI"
    isin: "ES0112602000"
    category: "Global Small/Mid-Cap Equity"
    morningstarId: "F000011HLY"
    comment: "Comentario2"
  - name: "Hamco Global Value Fund R FI"
    isin: "ES0141116030"
    category: "Global Small/Mid-Cap Equity"
    morningstarId: "F000014ACV"
    comment: "Comentario3"
plans:
  - name: "Myinvestor Indexado Global PP"
    isin: "N5396"
    category: "RVI GLOBAL"
    morningstarId: "F000016CB6"
    comment: "Comentario Plan"
