funds:
  - name: "Adarve Altea FI"
    isin: "ES0107474033"
    category: "Global Allocation - EUR"
    morningstarId: "F000010N72"
    comment: ""
  - name: "azValor Blue Chips FI"
    isin: "ES0112603008"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F00000Z1R8"
    comment: ""
  - name: "azValor Internacional FI"
    isin: "ES0112611001"
    category: "Global Flex-Cap Equity"
    morningstarId: "F00000WI0D"
    comment: ""
  - name: "azValor Managers FI"
    isin: "ES0112602000"
    category: "Global Small/Mid-Cap Equity"
    morningstarId: "F000011HLY"
    comment: ""
  - name: "Baelo Patrimonio FI"
    isin: "ES0113224003"
    category: "Global Allocation - EUR"
    morningstarId: "F00000Y11N"
    comment: ""
  - name: "Bestinver Internacional FI"
    isin: "ES0114638037"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F0GBR04F4Z"
    comment: ""
  - name: "Bestinver Latam FI"
    isin: "ES0114652038"
    category: "Latin America Equity"
    morningstarId: "F000000FUG"
    comment: ""
  - name: "Buy & Hold Luxemburgo"
    isin: "LU1865943433"
    category: "Global Allocation - EUR"
    morningstarId: "F000011043"
    comment: ""
  - name: "Cobas Internacional FI"
    isin: "ES0124035008"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F00000YIA4"
    comment: ""
  - name: "Cobas Selección FI"
    isin: "ES0124036006"
    category: "Global Flex-Cap Equity"
    morningstarId: "F00000YIA2"
    comment: ""
  - name: "Esfera I / Baelo Patrimonio FI"
    isin: "ES0113224003"
    category: "Global Allocation - EUR"
    morningstarId: "F00000Y11N"
    comment: ""
  - name: "Fidelity MSCI World Index Fund P-ACC-EUR"
    isin: "IE00BYX5NX33"
    category: "Global Large-Cap Blend Equity"
    morningstarId: "F00000Z91L"
    comment: ""
  - name: "Hamco Global Value Fund R FI"
    isin: "ES0141116030"
    category: "Global Small/Mid-Cap Equity"
    morningstarId: "F000014ACV"
    comment: ""
  - name: "Horos Value Internacional FI"
    isin: "ES0147900005"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F000010N3U"
    comment: ""
  - name: "Imprenta Global FI"
    isin: "ES0147690002"
    category: "Global Flex-Cap Equity"
    morningstarId: "F000011Q2O"
    comment: ""
  - name: "Magallanes European Equity M FI"
    isin: "ES0159259005"
    category: "Europe Flex-Cap Equity"
    morningstarId: "F00000VR37"
    comment: ""
  - name: "Magallanes Microcaps Europe C FI"
    isin: "ES0159203037"
    category: "Europe Small-Cap Equity"
    morningstarId: "F00000X66T"
    comment: ""
  - name: "Metavalor FI"
    isin: "ES0162734035"
    category: "Spain Equity"
    morningstarId: "F0GBR04KID"
    comment: ""
  - name: "Metavalor Internacional FI"
    isin: "ES0162721032"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F0GBR04KIG"
    comment: ""
  - name: "MyInvestor Nasdaq 100 FI"
    isin: "ES0164103023"
    category: "US Large-Cap Growth Equity"
    morningstarId: "F000012V3H"
    comment: ""
  - name: "MyInvestor S&P 500 Equiponderado FI"
    isin: "ES0164103007"
    category: "US Large-Cap Value Equity"
    morningstarId: "F000012V3K"
    comment: ""
  - name: "Numantia Patrimonio Global"
    isin: "ES0166699002"
    category: "Global Allocation - EUR"
    morningstarId: "F00000Y11O"
    comment: ""
  - name: "River Patrimonio FI"
    isin: "ES0173822007"
    category: "Global Allocation - EUR"
    morningstarId: "F0000140YV"
    comment: ""
  - name: "Robeco Global Consumer Trends F EUR"
    isin: "LU0187079347"
    category: "Sector Equity Consumer Goods and Services"
    morningstarId: "F0GBR04QZX"
    comment: ""
  - name: "Seilern World Growth U R"
    isin: "IE00B2NXKW18"
    category: "Global Large-Cap Growth Equity"
    morningstarId: "F000000B2L"
    comment: ""
  - name: "Sycomore Partners R"
    isin: "FR0010892233"
    category: "Europe Flex-Cap Equity"
    morningstarId: "F00000LUW2"
    comment: ""
  - name: "True Value FI"
    isin: "ES0180792006"
    category: "Global Flex-Cap Equity"
    morningstarId: "F00000S6U9"
    comment: ""
  - name: "Valentum FI"
    isin: "ES0180999008"
    category: "Global Large-Cap Value Equity"
    morningstarId: "F00000T4S2"
    comment: ""
  - name: "Vanguard Global Stock Index Fund EUR Acc"
    isin: "IE00B03HD191"
    category: "Global Large-Cap Blend Equity"
    morningstarId: "F000005HT1"
    comment: ""
  - name: "Vanguard U.S. 500 Stock Index Fund EUR Acc"
    isin: "IE0032126645"
    category: "US Large-Cap Blend Equity"
    morningstarId: "F0000002H1"
    comment: ""
  - name: "Vanguard Emerging Markets Stock Index Fund EUR Acc"
    isin: "IE0031786142"
    category: "Global Emerging Markets Equity"
    morningstarId: "F0000002GX"
    comment: ""
  - name: "Vanguard European Stock Index Fund EUR Acc"
    isin: "IE0007987690"
    category: "Europe Large-Cap Blend Equity"
    morningstarId: "F0000002H6"
    comment: ""
  - name: "Vanguard Japan Stock Index Fund EUR Acc"
    isin: "IE0007281425"
    category: "Japan Large-Cap Equity"
    morningstarId: "F0000002HA"
    comment: ""
  - name: "Vanguard Pacific Ex-Japan Stock Index Fund EUR Acc"
    isin: "IE0007201021"
    category: "Asia-Pacific ex-Japan Equity"
    morningstarId: "F0000002HD"
    comment: ""
plans:
  - name: "Bestinver Global PP"
    isin: "N0643"
    category: "RVI GLOBAL"
    morningstarId: "F000000EY8"
    comment: ""
  - name: "Cobas Global PP"
    isin: "N5322"
    category: "RVI GLOBAL"
    morningstarId: "F00000YI9U"
    comment: ""
  - name: "Caser Previsión Activa"
    isin: "N4732"
    category: "RV Mixta Internacional"
    morningstarId: "F00000WW78"
    comment: ""
  - name: "Myinvestor Indexado Global PP"
    isin: "N5396"
    category: "RVI GLOBAL"
    morningstarId: "F000016CB6"
    comment: ""
  - name: "MyInvestor S&P 500 PP"
    isin: "N5394"
    category: "RVI USA"
    morningstarId: "F000016CB7"
    comment: ""
  - name: "Naranja 2050"
    isin: "N3917"
    category: "Ciclo de Vida"
    morningstarId: "F00000P83H"
    comment: ""
